// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentManagementSystem.Repositories;

#nullable disable

namespace StudentManagementSystem.Migrations
{
    [DbContext(typeof(ConnectionContext))]
    [Migration("20240708155804_byxx")]
    partial class byxx
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StudentManagementSystem.Models.Studnet", b =>
                {
                    b.Property<int>("Stubent_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Stubent_Id"));

                    b.Property<DateTime>("Admission_date")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Fees")
                        .HasColumnType("double");

                    b.Property<string>("Mobile_Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stubent_Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Stubent_Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Student_Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Stubent_Id");

                    b.ToTable("Studentmang");
                });
#pragma warning restore 612, 618
        }
    }
}
